name: Playwright Cucumber Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment (qa, staging, prod)"
        required: true
        default: "qa"
      browser:
        description: "Select browser (chromium, firefox, webkit)"
        required: true
        default: "chromium"

permissions:
  contents: write
  pages: write
  id-token: write
  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      BROWSER: ${{ github.event.inputs.browser }}

      # Add your secret credentials here
      QA_USERNAME: ${{ secrets.QA_USERNAME }}
      QA_PASSWORD: ${{ secrets.QA_PASSWORD }}
      STAGING_USERNAME: ${{ secrets.STAGING_USERNAME }}
      STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
      PROD_USERNAME: ${{ secrets.PROD_USERNAME }}
      PROD_PASSWORD: ${{ secrets.PROD_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber tests (ignore failures so report still generates)
        run: npx cross-env ENV=${{ env.ENV }} BROWSER=${{ env.BROWSER }} npm run test || true

      - name: Generate Allure Report
        run: npm run allure:generate


      - name: Deploy Unique Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: reports/build-${{ github.run_number }}
          keep_files: true

      - name: Add Allure Report Link to Summary
        if: success() || failure()
        run: |
          REPORT_URL="https://minhalabbas000.github.io/Playwright-Ts-Cucumber-Allure/reports/build-${{ github.run_number }}/"
          echo "ðŸ”— **[View Allure Report for Build #${{ github.run_number }}](${REPORT_URL})**" >> $GITHUB_STEP_SUMMARY
          echo "Allure report for Build #${{ github.run_number }} available at: $REPORT_URL"
